#image: maven:3.5-jdk-8

# Define stages
#   Stages group various steps into one block,
#   if any step fails, the entire stage fails
stages:
- validate
- compile
- test

# Step definition
validate:
  # Stage the step belongs to
  stage: validate
  # Scipts to run for this step
  script:
  - mvn validate

#checkstyle:
#  stage: validate
#  script:
#  - mvn checkstyle:check
#  # Allow step to fail - treats failture as a warning
#  allow_failure: true

compile:
  stage: compile
  script:
  - mvn compile

test:
  stage: test
  script:
  - mvn test -B